### ISSUE TITLE
Delete user doesn't work

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#171]
JavaScript of detete button are commented.
https://github.com/isard-vdi/isard/blob/master/src/webapp/static/admin/js/users.js#L95

This JavaScript raises the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/socketio/server.py", line 636, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/lib/python3.6/site-packages/socketio/server.py", line 665, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/lib/python3.6/site-packages/flask_socketio/__init__.py", line 224, in _handler
    *args)
  File "/usr/lib/python3.6/site-packages/flask_socketio/__init__.py", line 591, in _handle_event
    ret = handler(*args)
  File "/isard/webapp/lib/isardSocketio.py", line 618, in socketio_user_delete
    res=app.adminapi.user_delete(form_data)
AttributeError: 'isardAdmin' object has no attribute 'user_delete'
Fri Jun 21 23:40:43 2019 <Thread at 0x7f1667d9ac28: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7f166803a358>>(<socketio.server.Server object at 0x7f166803a358>, 'f5b317d31cb44705aff9b0ce60bf36b2', ['user_delete', {'quota': {'hardware': {}, 'domain, '/sio_admins', None)> failed with AttributeError
```

**Comment by NefixEstrada** [comment]
While #177 is a temporary workaround, this still needs to be fixed!

**Comment by sim6** [comment]
Solved in `develop` branch. https://github.com/isard-vdi/isard/blob/master/src/webapp/static/admin/js/users.js#L95
