### ISSUE TITLE
Engine crash

### ISSUE THREAD

**Issue by sim6** [isard-vdi/isard#294]
```
2020/11/04 11:20:43 485 - ERROR - manager_pooling: libvirt can't connect to hypervisor isard-hypervisor
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/isard/engine/models/manager_hypervisors.py", line 394, in run
    self.test_hyps_and_start_threads()
  File "/isard/engine/models/manager_hypervisors.py", line 269, in test_hyps_and_start_threads
    set_domains_coherence(dict_hyps_ready)
  File "/isard/engine/services/threads/threads.py", line 365, in set_domains_coherence
    for domain_name, domain_obj in hyp_obj.domains.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by jvinolas** [comment]
Feel free to reopen it at gitlab.

**Issues from now on will only be held at https://gitlab.com/isard/isardvdi/-/issues**
