### ISSUE TITLE
Failed to execute script docker-compose Error when i try to pull the docker-compose.yml

### ISSUE THREAD

**Issue by nicrieser** [isard-vdi/isard#319]
whenever i try to pull the docker-compose ill get the following error:

Pulling isard-database   ...
Pulling isard-hypervisor ...
Pulling isard-app        ...
Pulling isard-nginx      ...

ERROR: for isard-app  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".')

ERROR: for isard-database  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".')

ERROR: for isard-nginx  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".')

ERROR: for isard-hypervisor  Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".')
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages\docker\credentials\store.py", line 35, in get
  File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 746, in pull
  File "compose\project.py", line 703, in pull
  File "compose\project.py", line 751, in parallel_pull
  File "compose\parallel.py", line 108, in parallel_execute
  File "compose\parallel.py", line 206, in producer
  File "compose\project.py", line 733, in pull_service
  File "compose\service.py", line 1234, in _do_pull
  File "site-packages\docker\api\image.py", line 396, in pull
  File "site-packages\docker\auth.py", line 48, in get_config_header
  File "site-packages\docker\auth.py", line 324, in resolve_authconfig
  File "site-packages\docker\auth.py", line 235, in resolve_authconfig
  File "site-packages\docker\auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `Element nicht gefunden.`".')
[2768] Failed to execute script docker-compose

**Comment by nicrieser** [comment]
i forgot to log in on docker destop. now its working

**Comment by sim6** [comment]
Thanks for using IsardVDI. We are focused on releasing version 2. You can download https://isardvdi.com/docker-compose.yml to use the latest `develop` version.
