### ISSUE TITLE
Broom fails to delete domain

### ISSUE THREAD

**Issue by jvinolas** [isard-vdi/isard#83]
Changing from a failed intermediate template creation status to Deleting makes broom exception:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/isard/engine/controllers/broom.py", line 129, in run
    self.polling()
  File "/isard/engine/controllers/broom.py", line 88, in polling
    if len(hyp_started) == 0:
TypeError: object of type 'bool' has no len()
```

**Comment by jvinolas** [comment]
This is fixed in 1.1
