### ISSUE TITLE
Can't contact isard engine.

### ISSUE THREAD

**Issue by gypsykanarak** [isard-vdi/isard#97]
i try to check again???

How to started : python3 run_engine.py ??

im deploy on nutanix server

**Comment by gypsykanarak** [comment]
when i start python3 run_engine.py
Engine log level: WARNING (30)
Traceback (most recent call last):
  File "run_engine.py", line 49, in <module>
    run(app)
  File "run_engine.py", line 20, in run
    http_server.serve_forever()
  File "/usr/lib/python3.6/site-packages/gevent/baseserver.py", line 360, in serve_forever
    self.start()
  File "/usr/lib/python3.6/site-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/usr/lib/python3.6/site-packages/gevent/pywsgi.py", line 1450, in init_socket
    StreamServer.init_socket(self)
  File "/usr/lib/python3.6/site-packages/gevent/server.py", line 127, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/lib/python3.6/site-packages/gevent/server.py", line 138, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/lib/python3.6/site-packages/gevent/server.py", line 229, in _tcp_listener
    sock.bind(address)
OSError: [Errno 98] Address in use: ('0.0.0.0', 5555)

**Comment by jvinolas** [comment]
Do not try to run IsardVDI without dockers. Use installation documentation: https://isardvdi.readthedocs.io/en/latest/install/install/

**Comment by jvinolas** [comment]
Also check if your environtment could be affected by bug #98 as we are just working on it.

**Comment by NefixEstrada** [comment]
Hello!

We've released IsardVDI 1.1.0. This release has probably fixed your issue so, could you try and check if the fixes work?

Thanks!

**Comment by NefixEstrada** [comment]
Closing due inactivity
